
[build]
command = "npm run generate"
publish = "dist"

[[redirects]]
from = "/blog/nomie-5-4-0-release"
status = 301
to = "/release/5.4"

[[redirects]]
from = "/blog/killing-native"
status = 301
to = "/release/4.0"

[[redirects]]
force = true
from = "/blog/nomie-5-introduction"
status = 301
to = "/release/5.0"

[[redirects]]
force = true
from = "/blog/open-sourcing-nomie"
status = 301
to = "/release/4.0"

[[redirects]]
force = true
from = "blog/original-nomie-blog-post"
status = 301
to = "/release/1.0"

[[redirects]]
force = true
from = "/blog/01-nomie-4-1-30-release"
status = 301
to = "/release/4.1"

[[redirects]]
force = true
from = "/blog/nomie-5-3-0-release"
status = 301
to = "/release/5.3"

[[redirects]]
from = "/blog/announcing-nomie-3-for-ios"
status = 301
to = "/release/3.0"

[[redirects]]
from = "/blog/preparing-for-nomie-3"
status = 301
to = "/release/3.0"

[[redirects]]
from = "/blog/nomie-3-0-5-release"
status = 301
to = "/release/3.0.5"

[[redirects]]
from = "/blog/nomie-3-0-7-release"
status = 301
to = "/release/3.0.7"

[[redirects]]
from = "/blog/nomie-3-for-android-progress"
status = 301
to = "/release/3.0"

[[redirects]]
from = "/nomie3-help"
status = 301
to = "/faq"

[[redirects]]
from = "/blog/nomie-pro-is-finally-ready"
status = 301
to = "/release/3.0"

[[redirects]]
from = "/blog/nomie-3-0-4-test"
status = 301
to = "/release/3.0"

[[redirects]]
from = "/podcast"
status = 301
to = "https://soundcloud.com/nomiepodcast"

[[redirects]]
from = "/blog/nomie-4-4-0-video-podcast"
status = 301
to = "/release/4.4"

[[redirects]]
from = "/podcast/*"
status = 301
to = "https://soundcloud.com/nomiepodcast"

[[redirects]]
from = "/blog"
status = 301
to = "/release"

[[redirects]]
from = "/podcast/*"
status = 301
to = "https://soundcloud.com/nomiepodcast"

[[redirects]]
from = "/tutorials/creating-an-export-nomie-1-2"
status = 301
to = "/tutorials/upgrading-nomie"

[[redirects]]
from = "/opensource"
status = 301
to = "https://github.com/open-nomie/nomie"

# [[redirects]]
# from = "/*"
# status = 404
# to = "/index.html"
